outputs = "Active"

position = "Top"

enable_esc_key = true

[modules]
left = ["Workspaces"]
center = ["WindowTitle"]
right = [["Clock", "Privacy", "Settings]]

[settings]
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"

lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true
remove_idle_btn = true


[appearance]
font_name = "Comic Sans MS"

style = "Island"

opacity = 0.8

[appearance.menu]
opacity = 0.7
backdrop = 0.3

[appearance.background_color]
base = "#448877"
strong = "#448888"
weak = "#448855"
text = "#ffffff"[appearance]

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
